(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function q(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.h=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ea(a){return a.raw=a}function t(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var fa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};q("Object.assign",function(a){return a||fa});
var ha="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function v(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.M=b.prototype}function na(){this.l=!1;this.h=null;this.m=void 0;this.i=1;this.s=0;this.j=null}function oa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}na.prototype.o=function(a){this.m=a};function pa(a,b){a.j={sa:b,za:!0};a.i=a.s}
na.prototype.return=function(a){this.j={return:a};this.i=this.s};function qa(a){this.h=new na;this.i=a}function ra(a,b){oa(a.h);var c=a.h.h;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.h.return);a.h.return(b);return ta(a)}
function sa(a,b,c,d){try{var e=b.call(a.h.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.h.l=!1,e;var f=e.value}catch(g){return a.h.h=null,pa(a.h,g),ta(a)}a.h.h=null;d.call(a.h,f);return ta(a)}function ta(a){for(;a.h.i;)try{var b=a.i(a.h);if(b)return a.h.l=!1,{value:b.value,done:!1}}catch(c){a.h.m=void 0,pa(a.h,c)}a.h.l=!1;if(a.h.j){b=a.h.j;a.h.j=null;if(b.za)throw b.sa;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ua(a){this.next=function(b){oa(a.h);a.h.h?b=sa(a,a.h.h.next,b,a.h.o):(a.h.o(b),b=ta(a));return b};this.throw=function(b){oa(a.h);a.h.h?b=sa(a,a.h.h["throw"],b,a.h.o):(pa(a.h,b),b=ta(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function va(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function wa(a){return va(new ua(new qa(a)))}function xa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
q("Promise",function(a){function b(g){this.h=0;this.j=void 0;this.i=[];this.s=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.h=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.i=function(g){if(null==this.h){this.h=[];var h=this;this.j(function(){h.m()})}this.h.push(g)};var e=p.setTimeout;c.prototype.j=function(g){e(g,0)};c.prototype.m=function(){for(;this.h&&this.h.length;){var g=this.h;this.h=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.l(l)}}}this.h=null};c.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.G),reject:g(this.m)}};b.prototype.G=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.N(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.D(g):this.o(g)}};
b.prototype.D=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}"function"==typeof h?this.O(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(0!=this.h)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.j=h;2===this.h&&this.J();this.A()};b.prototype.J=function(){var g=this;e(function(){if(g.C()){var h=p.console;"undefined"!==typeof h&&h.error(g.j)}},1)};b.prototype.C=
function(){if(this.s)return!1;var g=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=p.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return k(g)};b.prototype.A=function(){if(null!=this.i){for(var g=0;g<this.i.length;++g)f.i(this.i[g]);this.i=null}};var f=new c;b.prototype.N=
function(g){var h=this.l();g.U(h.resolve,h.reject)};b.prototype.O=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(y,z){return"function"==typeof y?function(db){try{l(y(db))}catch(eb){m(eb)}}:z}var l,m,r=new b(function(y,z){l=y;m=z});this.U(k(g,l),k(h,m));return r};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.U=function(g,h){function k(){switch(l.h){case 1:g(l.j);break;case 2:h(l.j);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;null==this.i?f.i(k):this.i.push(k);this.s=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=t(g),m=l.next();!m.done;m=l.next())d(m.value).U(h,k)})};b.all=function(g){var h=t(g),k=h.next();return k.done?d([]):new b(function(l,m){function r(db){return function(eb){y[db]=eb;z--;0==z&&l(y)}}var y=[],z=0;do y.push(void 0),z++,d(k.value).U(r(y.length-1),m),k=h.next();while(!k.done)})};return b});
q("WeakMap",function(a){function b(k){this.h=(h+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!u(k,g)){var l=new c;ba(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(r){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.h]=l;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.h]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.h)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.h)?delete k[g][this.h]:!1};return b});
q("Map",function(a){function b(){var h={};return h.I=h.next=h.head=h}function c(h,k){var l=h.h;return da(function(){if(l){for(;l.head!=h.h;)l=l.I;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;"object"==l||"function"==l?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h.i[l];if(m&&u(h.i,l))for(h=0;h<m.length;h++){var r=m[h];if(k!==k&&r.key!==r.key||k===r.key)return{id:l,list:m,index:h,B:r}}return{id:l,list:m,
index:-1,B:void 0}}function e(h){this.i={};this.h=b();this.size=0;if(h){h=t(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(t([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(r){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.i[l.id]=[]);l.B?l.B.value=k:(l.B={next:this.h,I:this.h.I,head:this.h,key:h,value:k},l.list.push(l.B),this.h.I.next=l.B,this.h.I=l.B,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.B&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.i[h.id],h.B.I.next=h.B.next,h.B.next.I=h.B.I,h.B.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.i={};this.h=this.h.I=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).B};e.prototype.get=function(h){return(h=d(this,h).B)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});q("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});
function ya(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return ya(this,function(b,c){return[b,c]})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});q("Array.prototype.keys",function(a){return a?a:function(){return ya(this,function(b){return b})}});
q("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function w(a){return a?a:Array.prototype.fill}q("Int8Array.prototype.fill",w);q("Uint8Array.prototype.fill",w);q("Uint8ClampedArray.prototype.fill",w);q("Int16Array.prototype.fill",w);q("Uint16Array.prototype.fill",w);q("Int32Array.prototype.fill",w);
q("Uint32Array.prototype.fill",w);q("Float32Array.prototype.fill",w);q("Float64Array.prototype.fill",w);q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
q("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var za=za||{},x=this||self;
function Aa(a,b){a=a.split(".");var c=x;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Ba(a,b){a=a.split(".");b=b||x;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function Ca(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}
function Da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var Ea="closure_uid_"+(1E9*Math.random()>>>0),Fa=0;function Ga(a,b,c){return a.call.apply(a.bind,arguments)}function Ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function A(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?A=Ga:A=Ha;return A.apply(null,arguments)}function B(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function Ia(a){(0,eval)(a)}
function C(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ea=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function Ja(a){return a};function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b);this.h=!0}C(D,Error);D.prototype.name="CustomError";var Ka;var La=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ma=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Na=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Oa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function Pa(a,b){b=La(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}
function Qa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ra(){var a=x.navigator;return a&&(a=a.userAgent)?a:""}function E(a){return-1!=Ra().indexOf(a)};function Sa(a){Sa[" "](a);return a}Sa[" "]=function(){};var Ta=E("Trident")||E("MSIE"),Ua=E("Gecko")&&!(-1!=Ra().toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),Va=-1!=Ra().toLowerCase().indexOf("webkit")&&!E("Edge")&&E("Mobile");try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function Wa(){};function Xa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Ya(a){var b={},c;for(c in a)b[c]=a[c];return b}var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function $a(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var ab;function F(a,b){this.h=b===bb?a:""}F.prototype.toString=function(){return this.h+""};F.prototype.ya=!0;F.prototype.ua=function(){return this.h.toString()};function cb(a){return a instanceof F&&a.constructor===F?a.h:"type_error:TrustedResourceUrl"}var bb={};
function fb(a){if(void 0===ab){var b=null;var c=x.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("asx-frontend#html",{createHTML:Ja,createScript:Ja,createScriptURL:Ja})}catch(d){x.console&&x.console.error(d.message)}ab=b}else ab=b}a=(b=ab)?b.createScriptURL(a):a;return new F(a,bb)};function gb(a,b){var c=hb(a.ownerDocument&&a.ownerDocument.defaultView);c&&a.setAttribute("nonce",c);a.src=cb(b)}var ib=/^[\w+/_-]+[=]{0,2}$/;function hb(a){a=(a||x).document;return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ib.test(a)?a:"":""};function jb(a,b){Xa(b,function(c,d){c&&"object"==typeof c&&c.ya&&(c=c.ua());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:kb.hasOwnProperty(d)?a.setAttribute(kb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var kb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function lb(a,b,c){var d=arguments,e=document,f=d[1],g=mb(e,String(d[0]));f&&("string"===typeof f?g.className=f:Array.isArray(f)?g.className=f.join(" "):jb(g,f));2<d.length&&nb(e,g,d);return g}
function nb(a,b,c){function d(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var f=c[e];if(!Ca(f)||Da(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(Da(f)){var g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){g="function"==typeof f.item;break a}}g=!1}Ma(g?Qa(f):f,d)}}}function mb(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function ob(a){this.h=a||x.document||document};function pb(a){x.setTimeout(function(){throw a;},0)};var qb={},rb=null;var sb="undefined"!==typeof Uint8Array,tb=!Ta&&"function"===typeof x.btoa;
function ub(a){if(!tb){var b;void 0===b&&(b=0);if(!rb){rb={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));qb[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===rb[h]&&(rb[h]=g)}}}b=qb[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var k=a[f],l=a[f+1];h=a[f+2];g=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];c[e++]=""+g+k+l+h}g=0;h=d;switch(a.length-
f){case 2:g=a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=""+b[a>>2]+b[(a&3)<<4|g>>4]+h+d}return c.join("")}for(b="";10240<a.length;)b+=String.fromCharCode.apply(null,a.subarray(0,10240)),a=a.subarray(10240);b+=String.fromCharCode.apply(null,a);return btoa(b)}var vb={};var wb;function xb(a){if(vb!==vb)throw Error("illegal external caller");this.ma=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");};var G="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;function yb(a,b){if(G)return a[G]|=b;if(void 0!==a.L)return a.L|=b;Object.defineProperties(a,{L:{value:b,configurable:!0,writable:!0,enumerable:!1}});return b}function H(a){var b;G?b=a[G]:b=a.L;return null==b?0:b}function I(a,b){G?a[G]=b:void 0!==a.L?a.L=b:Object.defineProperties(a,{L:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function zb(a){yb(a,16);return a}function Ab(a,b){I(b,(a|0)&-51)}
function Bb(a,b){I(b,(a|18)&-41)};var Cb={};function Db(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Eb,Fb=[];I(Fb,23);Eb=Object.freeze(Fb);function Gb(a){if(H(a.u)&2)throw Error("Cannot mutate an immutable Message");}function Hb(a){var b=a.length;(b=b?a[b-1]:void 0)&&Db(b)?b.g=1:(b={},a.push((b.g=1,b)))};function Ib(a){return a.displayName||a.name||"unknown type name"}function Jb(a,b){if(!(a instanceof b))throw Error("Expected instanceof "+Ib(b)+" but got "+(a&&Ib(a.constructor)));};function Kb(a){var b=a.i+a.K;return a.F||(a.F=a.u[b]={})}function Lb(a,b,c){return-1===b?null:b>=a.i?a.F?a.F[b]:void 0:c&&a.F&&(c=a.F[b],null!=c)?c:a.u[b+a.K]}function J(a,b,c,d){a.j&&(a.j=void 0);if(b>=a.i||d)return Kb(a)[b]=c,a;a.u[b+a.K]=c;(c=a.F)&&b in c&&delete c[b];return a}function K(a,b){Gb(a);J(a,b,void 0,!1);return a}function L(a,b){a=Lb(a,b);a=null==a?a:!!a;return null==a?!1:a};var Mb;function Nb(a,b){Mb=b;a=new a(b);Mb=void 0;return a};function Ob(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a)if(Array.isArray(a)){if(0!==(H(a)&128))return a=Array.prototype.slice.call(a),Hb(a),a}else{if(sb&&null!=a&&a instanceof Uint8Array)return ub(a);if(a instanceof xb){var b=a.ma;return null==b?"":"string"===typeof b?b:a.ma=ub(b)}}}return a};function Pb(a,b,c,d){if(null!=a){if(Array.isArray(a))a=Qb(a,b,c,void 0!==d);else if(Db(a)){var e={},f;for(f in a)e[f]=Pb(a[f],b,c,d);a=e}else a=b(a,d);return a}}function Qb(a,b,c,d){var e=H(a);d=d?!!(e&16):void 0;a=Array.prototype.slice.call(a);for(var f=0;f<a.length;f++)a[f]=Pb(a[f],b,c,d);c(e,a);return a}function Rb(a){return a.aa===Cb?a.toJSON():Ob(a)}function Sb(a,b){a&128&&Hb(b)};function Tb(a,b,c){c=void 0===c?Bb:c;if(null!=a){if(sb&&a instanceof Uint8Array)return a.length?new xb(new Uint8Array(a)):wb||(wb=new xb(null));if(Array.isArray(a)){var d=H(a);if(d&2)return a;if(b&&!(d&32)&&(d&16||0===d))return I(a,d|2),a;a=Qb(a,Tb,d&4?Bb:c,!0);b=H(a);b&4&&b&2&&Object.freeze(a);return a}return a.aa===Cb?Ub(a):a}}
function Vb(a,b,c,d,e,f,g){if(a=a.h&&a.h[c]){d=0<a.length?a[0].constructor:void 0;f=H(a);f&2||(a=Na(a,Ub),Bb(f,a),Object.freeze(a));Gb(b);null==a?f=Eb:(f=[],yb(f,1));g=f;if(null!=a){f=!!a.length;for(var h=0;h<a.length;h++){var k=a[h];Jb(k,d);f=f&&!(H(k.u)&2);g[h]=k.u}d=g;f=(f?8:0)|1;g=H(d);(g&f)!==f&&(Object.isFrozen(d)&&(d=Array.prototype.slice.call(d)),I(d,g|f));g=d;b.h||(b.h={});b.h[c]=a}else b.h&&(b.h[c]=void 0);J(b,c,g,e)}else d=Tb(d,f,g),Gb(b),J(b,c,d,e)}
function Ub(a){if(H(a.u)&2)return a;a=Wb(a,!0);yb(a.u,2);return a}function Wb(a,b){var c=a.u,d=zb([]),e=a.constructor.h;e&&d.push(e);e=a.F;if(e){d.length=c.length;d.fill(void 0,d.length,c.length);var f={};d[d.length-1]=f}0!==(H(c)&128)&&Hb(d);b=b||H(a.u)&2?Bb:Ab;d=Nb(a.constructor,d);a.ga&&(d.ga=a.ga.slice());f=!!(H(c)&16);for(var g=e?c.length-1:c.length,h=0;h<g;h++)Vb(a,d,h-a.K,c[h],!1,f,b);if(e)for(var k in e)c=e[k],g=+k,Number.isNaN(g),Vb(a,d,g,c,!0,f,b);return d};function M(a,b,c){null==a&&(a=Mb);Mb=void 0;var d=this.constructor.i||0,e=0<d,f=this.constructor.h,g=!1;if(null==a){a=f?[f]:[];var h=48;var k=!0;e&&(d=0,h|=128);I(a,h)}else{if(!Array.isArray(a))throw Error();if(f&&f!==a[0])throw Error();var l=h=yb(a,0);if(k=0!==(16&l))(g=0!==(32&l))||(l|=32);if(e)if(128&l)d=0;else{if(0<a.length){var m=a[a.length-1];if(Db(m)&&"g"in m){d=0;l|=128;delete m.g;var r=!0,y;for(y in m){r=!1;break}r&&a.pop()}}}else if(128&l)throw Error();h!==l&&I(a,l)}this.K=(f?0:-1)-d;this.h=
void 0;this.u=a;a:{f=this.u.length;d=f-1;if(f&&(f=this.u[d],Db(f))){this.F=f;this.i=d-this.K;break a}void 0!==b&&-1<b?(this.i=Math.max(b,d+1-this.K),this.F=void 0):this.i=Number.MAX_VALUE}if(!e&&this.F&&"g"in this.F)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(c){b=k&&!g&&!0;e=this.i;var z;for(k=0;k<c.length;k++)g=c[k],g<e?(g+=this.K,(d=a[g])?Xb(d,b):a[g]=Eb):(z||(z=Kb(this)),(d=z[g])?Xb(d,b):z[g]=Eb)}}
M.prototype.toJSON=function(){return Qb(this.u,Rb,Sb)};function Xb(a,b){if(Array.isArray(a)){var c=H(a),d=1;!b||c&2||(d|=16);(c&d)!==d&&I(a,c|d)}}M.prototype.aa=Cb;M.prototype.toString=function(){return this.u.toString()};function Yb(a,b){this.j=a;this.l=b;this.i=0;this.h=null}Yb.prototype.get=function(){if(0<this.i){this.i--;var a=this.h;this.h=a.next;a.next=null}else a=this.j();return a};function Zb(a,b){a.l(b);100>a.i&&(a.i++,b.next=a.h,a.h=b)};var $b=[],ac=[],bc=!1;function cc(a){$b[$b.length]=a;if(bc)for(var b=0;b<ac.length;b++)a(A(ac[b].h,ac[b]))};var dc;
function ec(){var a=x.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!E("Presto")&&(a=function(){var e=mb(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=A(function(k){if(("*"==h||k.origin==h)&&k.data==g)this.port1.onmessage()},this);
f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!E("Trident")&&!E("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.fa;c.fa=null;e()}};return function(e){d.next={fa:e};d=d.next;b.port2.postMessage(0)}}return function(e){x.setTimeout(e,0)}}function fc(a){return a}cc(function(a){fc=a});function gc(){this.i=this.h=null}gc.prototype.add=function(a,b){var c=hc.get();c.set(a,b);this.i?this.i.next=c:this.h=c;this.i=c};function ic(){var a=jc,b=null;a.h&&(b=a.h,a.h=a.h.next,a.h||(a.i=null),b.next=null);return b}var hc=new Yb(function(){return new kc},function(a){return a.reset()});function kc(){this.next=this.scope=this.h=null}kc.prototype.set=function(a,b){this.h=a;this.scope=b;this.next=null};kc.prototype.reset=function(){this.next=this.scope=this.h=null};var lc,mc=!1,jc=new gc;function nc(a,b){lc||oc();mc||(lc(),mc=!0);jc.add(a,b)}function oc(){if(x.Promise&&x.Promise.resolve){var a=x.Promise.resolve(void 0);lc=function(){a.then(pc)}}else lc=function(){var b=pc;b=fc(b);"function"!==typeof x.setImmediate||x.Window&&x.Window.prototype&&!E("Edge")&&x.Window.prototype.setImmediate==x.setImmediate?(dc||(dc=ec()),dc(b)):x.setImmediate(b)}}function pc(){for(var a;a=ic();){try{a.h.call(a.scope)}catch(b){pb(b)}Zb(hc,a)}mc=!1};function qc(a){var b=Ba("window.location.href");null==a&&(a='Unknown Error of type "null/undefined"');if("string"===typeof a)return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(g){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||x.$googDebugFname||b}catch(g){e="Not available",c=!0}b=rc(a);if(!(!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name)){c=a.message;if(null==
c){if(a.constructor&&a.constructor instanceof Function){if(a.constructor.name)c=a.constructor.name;else if(c=a.constructor,sc[c])c=sc[c];else{c=String(c);if(!sc[c]){var f=/function\s+([^\(]+)/m.exec(c);sc[c]=f?f[1]:"[Anonymous]"}c=sc[c]}c='Unknown Error of type "'+c+'"'}else c="Unknown Error of unknown type";"function"===typeof a.toString&&Object.prototype.toString!==a.toString&&(c+=": "+a.toString())}return{message:c,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:b||"Not available"}}a.stack=
b;return{message:a.message,name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:a.stack}}function rc(a,b){b||(b={});b[tc(a)]=!0;var c=a.stack||"";(a=a.cause)&&!b[tc(a)]&&(c+="\nCaused by: ",a.stack&&0==a.stack.indexOf(a.toString())||(c+="string"===typeof a?a:a.message+"\n"),c+=rc(a,b));return c}function tc(a){var b="";"function"===typeof a.toString&&(b=""+a);return b+a.stack}var sc={};function N(){this.m=this.m;this.s=this.s}N.prototype.m=!1;N.prototype.isDisposed=function(){return this.m};N.prototype.Z=function(){this.m||(this.m=!0,this.H())};N.prototype.H=function(){if(this.s)for(;this.s.length;)this.s.shift()()};function O(a,b){this.type=a;this.h=this.target=b;this.defaultPrevented=!1}O.prototype.i=function(){this.defaultPrevented=!0};function P(a,b){O.call(this,a?a.type:"");this.relatedTarget=this.h=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.j=null;a&&this.init(a,b)}C(P,O);var uc={2:"touch",3:"pen",4:"mouse"};
P.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.h=b;if(b=a.relatedTarget){if(Ua){a:{try{Sa(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||
0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:uc[a.pointerType]||"";this.state=a.state;this.j=a;a.defaultPrevented&&P.M.i.call(this)};
P.prototype.i=function(){P.M.i.call(this);var a=this.j;a.preventDefault?a.preventDefault():a.returnValue=!1};var vc="closure_listenable_"+(1E6*Math.random()|0);var wc=0;function xc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.W=e;this.key=++wc;this.R=this.T=!1}function yc(a){a.R=!0;a.listener=null;a.proxy=null;a.src=null;a.W=null};function zc(a){this.src=a;this.h={};this.i=0}zc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.h[f];a||(a=this.h[f]=[],this.i++);var g=Ac(a,b,d,e);-1<g?(b=a[g],c||(b.T=!1)):(b=new xc(b,this.src,f,!!d,e),b.T=c,a.push(b));return b};function Bc(a,b){var c=b.type;c in a.h&&Pa(a.h[c],b)&&(yc(b),0==a.h[c].length&&(delete a.h[c],a.i--))}function Ac(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.R&&f.listener==b&&f.capture==!!c&&f.W==d)return e}return-1};var Cc="closure_lm_"+(1E6*Math.random()|0),Dc={},Ec=0;function Fc(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Fc(a,b[f],c,d,e);else(d=Da(d)?!!d.capture:!!d,c=Gc(c),a&&a[vc])?(a=a.j,b=String(b).toString(),b in a.h&&(f=a.h[b],c=Ac(f,c,d,e),-1<c&&(yc(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.h[b],a.i--)))):a&&(a=Hc(a))&&(b=a.h[b.toString()],a=-1,b&&(a=Ac(b,c,d,e)),(c=-1<a?b[a]:null)&&Ic(c))}
function Ic(a){if("number"!==typeof a&&a&&!a.R){var b=a.src;if(b&&b[vc])Bc(b.j,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(c in Dc?Dc[c]:Dc[c]="on"+c,d):b.addListener&&b.removeListener&&b.removeListener(d);Ec--;(c=Hc(b))?(Bc(c,a),0==c.i&&(c.src=null,b[Cc]=null)):yc(a)}}}function Jc(a,b){if(a.R)a=!0;else{b=new P(b,this);var c=a.listener,d=a.W||a.src;a.T&&Ic(a);a=c.call(d,b)}return a}
function Hc(a){a=a[Cc];return a instanceof zc?a:null}var Kc="__closure_events_fn_"+(1E9*Math.random()>>>0);function Gc(a){if("function"===typeof a)return a;a[Kc]||(a[Kc]=function(b){return a.handleEvent(b)});return a[Kc]}cc(function(a){Jc=a(Jc)});function Q(){N.call(this);this.j=new zc(this);this.pa=this;this.O=null}C(Q,N);Q.prototype[vc]=!0;Q.prototype.removeEventListener=function(a,b,c,d){Fc(this,a,b,c,d)};
function R(a,b){var c=a.O;if(c){var d=[];for(var e=1;c;c=c.O)d.push(c),++e}a=a.pa;c=b.type||b;"string"===typeof b?b=new O(b,a):b instanceof O?b.target=b.target||a:(e=b,b=new O(c,a),$a(b,e));e=!0;if(d)for(var f=d.length-1;0<=f;f--){var g=b.h=d[f];e=Lc(g,c,!0,b)&&e}g=b.h=a;e=Lc(g,c,!0,b)&&e;e=Lc(g,c,!1,b)&&e;if(d)for(f=0;f<d.length;f++)g=b.h=d[f],e=Lc(g,c,!1,b)&&e}
Q.prototype.H=function(){Q.M.H.call(this);if(this.j){var a=this.j,b=0,c;for(c in a.h){for(var d=a.h[c],e=0;e<d.length;e++)++b,yc(d[e]);delete a.h[c];a.i--}}this.O=null};function Lc(a,b,c,d){b=a.j.h[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.R&&g.capture==c){var h=g.listener,k=g.W||g.src;g.T&&Bc(a.j,g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};function Mc(a){try{return x.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function Nc(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};function Oc(){}Oc.prototype.i=null;function Pc(a){return a.i||(a.i=a.l())};var Qc;function Rc(){}C(Rc,Oc);Rc.prototype.h=function(){var a=Sc(this);return a?new ActiveXObject(a):new XMLHttpRequest};Rc.prototype.l=function(){var a={};Sc(this)&&(a[0]=!0,a[1]=!0);return a};
function Sc(a){if(!a.j&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.j=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.j}Qc=new Rc;function Tc(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function S(a){this.h=0;this.s=void 0;this.l=this.i=this.j=null;this.m=this.o=!1;if(a!=Wa)try{var b=this;a.call(void 0,function(c){T(b,2,c)},function(c){T(b,3,c)})}catch(c){T(this,3,c)}}function Uc(){this.next=this.j=this.i=this.l=this.h=null;this.m=!1}Uc.prototype.reset=function(){this.j=this.i=this.l=this.h=null;this.m=!1};var Vc=new Yb(function(){return new Uc},function(a){a.reset()});function Wc(a,b,c){var d=Vc.get();d.l=a;d.i=b;d.j=c;return d}
function U(a){if(a instanceof S)return a;var b=new S(Wa);T(b,2,a);return b}function Xc(a,b,c){Yc(a,b,c,null)||nc(B(b,a))}function Zc(a){return new S(function(b){var c=a.length,d=[];if(c)for(var e=function(h,k,l){c--;d[h]=k?{ta:!0,value:l}:{ta:!1,reason:l};0==c&&b(d)},f=0,g;f<a.length;f++)g=a[f],Xc(g,B(e,f,!0),B(e,f,!1));else b(d)})}S.prototype.then=function(a,b,c){return $c(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};S.prototype.$goog_Thenable=!0;
function ad(a,b){return $c(a,null,b)}S.prototype.cancel=function(a){if(0==this.h){var b=new bd(a);nc(function(){cd(this,b)},this)}};function cd(a,b){if(0==a.h)if(a.j){var c=a.j;if(c.i){for(var d=0,e=null,f=null,g=c.i;g&&(g.m||(d++,g.h==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.h&&1==d?cd(c,b):(f?(d=f,d.next==c.l&&(c.l=d),d.next=d.next.next):dd(c),ed(c,e,3,b)))}a.j=null}else T(a,3,b)}function fd(a,b){a.i||2!=a.h&&3!=a.h||gd(a);a.l?a.l.next=b:a.i=b;a.l=b}
function $c(a,b,c,d){var e=Wc(null,null,null);e.h=new S(function(f,g){e.l=b?function(h){try{var k=b.call(d,h);f(k)}catch(l){g(l)}}:f;e.i=c?function(h){try{var k=c.call(d,h);void 0===k&&h instanceof bd?g(h):f(k)}catch(l){g(l)}}:g});e.h.j=a;fd(a,e);return e.h}S.prototype.A=function(a){this.h=0;T(this,2,a)};S.prototype.C=function(a){this.h=0;T(this,3,a)};
function T(a,b,c){0==a.h&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.h=1,Yc(c,a.A,a.C,a)||(a.s=c,a.h=b,a.j=null,gd(a),3!=b||c instanceof bd||hd(a,c)))}function Yc(a,b,c,d){if(a instanceof S)return fd(a,Wc(b||Wa,c||null,d)),!0;if(Tc(a))return a.then(b,c,d),!0;if(Da(a))try{var e=a.then;if("function"===typeof e)return id(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1}
function id(a,b,c,d,e){function f(k){h||(h=!0,d.call(e,k))}function g(k){h||(h=!0,c.call(e,k))}var h=!1;try{b.call(a,g,f)}catch(k){f(k)}}function gd(a){a.o||(a.o=!0,nc(a.v,a))}function dd(a){var b=null;a.i&&(b=a.i,a.i=b.next,b.next=null);a.i||(a.l=null);return b}S.prototype.v=function(){for(var a;a=dd(this);)ed(this,a,this.h,this.s);this.o=!1};
function ed(a,b,c,d){if(3==c&&b.i&&!b.m)for(;a&&a.m;a=a.j)a.m=!1;if(b.h)b.h.j=null,jd(b,c,d);else try{b.m?b.l.call(b.j):jd(b,c,d)}catch(e){kd.call(null,e)}Zb(Vc,b)}function jd(a,b,c){2==b?a.l.call(a.j,c):a.i&&a.i.call(a.j,c)}function hd(a,b){a.m=!0;nc(function(){a.m&&kd.call(null,b)})}var kd=pb;function bd(a){D.call(this,a);this.h=!1}C(bd,D);bd.prototype.name="cancel";function ld(a,b,c){if("function"===typeof a)c&&(a=A(a,c));else if(a&&"function"==typeof a.handleEvent)a=A(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:x.setTimeout(a,b||0)};var md=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function nd(a){a=a.match(md)[1]||null;!a&&x.self&&x.self.location&&(a=x.self.location.protocol.slice(0,-1));return a?a.toLowerCase():""}
function od(a,b){if(!b)return a;var c=a.indexOf("#");0>c&&(c=a.length);var d=a.indexOf("?");if(0>d||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}function pd(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)pd(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}function qd(a,b){var c=[];for(b=b||0;b<a.length;b+=2)pd(a[b],a[b+1],c);return c.join("&")}
function rd(a){var b=[],c;for(c in a)pd(c,a[c],b);return b.join("&")}function sd(a,b){var c=2==arguments.length?qd(arguments[1],0):qd(arguments,1);return od(a,c)};function td(a){Q.call(this);this.headers=new Map;this.D=a||null;this.i=!1;this.C=this.h=null;this.N="";this.l=this.J=this.o=this.G=!1;this.A=0;this.v=null;this.ca="";this.X=this.Y=!1}C(td,Q);var ud=/^https?$/i,vd=["POST","PUT"],wd=[];function xd(a,b,c,d,e,f,g){var h=new td;wd.push(h);b&&h.j.add("complete",b,!1,void 0,void 0);h.j.add("ready",h.qa,!0,void 0,void 0);f&&(h.A=Math.max(0,f));g&&(h.Y=g);yd(h,a,c,d,e)}n=td.prototype;n.qa=function(){this.Z();Pa(wd,this)};
function yd(a,b,c,d,e){if(a.h)throw Error("[goog.net.XhrIo] Object is active with another request="+a.N+"; newUri="+b);c=c?c.toUpperCase():"GET";a.N=b;a.G=!1;a.i=!0;a.h=a.D?a.D.h():Qc.h();a.C=a.D?Pc(a.D):Pc(Qc);a.h.onreadystatechange=A(a.ha,a);try{a.J=!0,a.h.open(c,String(b),!0),a.J=!1}catch(h){zd(a);return}b=d||"";d=new Map(a.headers);if(e)if(Object.getPrototypeOf(e)===Object.prototype)for(var f in e)d.set(f,e[f]);else if("function"===typeof e.keys&&"function"===typeof e.get){f=t(e.keys());for(var g=
f.next();!g.done;g=f.next())g=g.value,d.set(g,e.get(g))}else throw Error("Unknown input type for opt_headers: "+String(e));e=Array.from(d.keys()).find(function(h){return"content-type"==h.toLowerCase()});f=x.FormData&&b instanceof x.FormData;!(0<=La(vd,c))||e||f||d.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");c=t(d);for(e=c.next();!e.done;e=c.next())d=t(e.value),e=d.next().value,d=d.next().value,a.h.setRequestHeader(e,d);a.ca&&(a.h.responseType=a.ca);"withCredentials"in a.h&&
a.h.withCredentials!==a.Y&&(a.h.withCredentials=a.Y);try{Ad(a),0<a.A&&(a.X=Bd(a.h),a.X?(a.h.timeout=a.A,a.h.ontimeout=A(a.S,a)):a.v=ld(a.S,a.A,a)),a.o=!0,a.h.send(b),a.o=!1}catch(h){zd(a)}}function Bd(a){return Ta&&"number"===typeof a.timeout&&void 0!==a.ontimeout}n.S=function(){"undefined"!=typeof za&&this.h&&(R(this,"timeout"),this.abort(8))};function zd(a){a.i=!1;a.h&&(a.l=!0,a.h.abort(),a.l=!1);Cd(a);Dd(a)}function Cd(a){a.G||(a.G=!0,R(a,"complete"),R(a,"error"))}
n.abort=function(){this.h&&this.i&&(this.i=!1,this.l=!0,this.h.abort(),this.l=!1,R(this,"complete"),R(this,"abort"),Dd(this))};n.H=function(){this.h&&(this.i&&(this.i=!1,this.l=!0,this.h.abort(),this.l=!1),Dd(this,!0));td.M.H.call(this)};n.ha=function(){this.isDisposed()||(this.J||this.o||this.l?Ed(this):this.ba())};n.ba=function(){Ed(this)};
function Ed(a){if(a.i&&"undefined"!=typeof za&&(!a.C[1]||4!=(a.h?a.h.readyState:0)||2!=Fd(a)))if(a.o&&4==(a.h?a.h.readyState:0))ld(a.ha,0,a);else if(R(a,"readystatechange"),4==(a.h?a.h.readyState:0)){a.i=!1;try{var b=Fd(a),c;if(!(c=Nc(b))){var d;if(d=0===b){var e=nd(String(a.N));d=!ud.test(e)}c=d}c?(R(a,"complete"),R(a,"success")):Cd(a)}finally{Dd(a)}}}function Dd(a,b){if(a.h){Ad(a);var c=a.h,d=a.C[0]?function(){}:null;a.h=null;a.C=null;b||R(a,"ready");try{c.onreadystatechange=d}catch(e){}}}
function Ad(a){a.h&&a.X&&(a.h.ontimeout=null);a.v&&(x.clearTimeout(a.v),a.v=null)}n.isActive=function(){return!!this.h};function Fd(a){try{return 2<(a.h?a.h.readyState:0)?a.h.status:-1}catch(b){return-1}}cc(function(a){td.prototype.ba=a(td.prototype.ba)});/*

 SPDX-License-Identifier: Apache-2.0
*/
function Gd(a){var b=xa.apply(1,arguments);if(0===b.length)return fb(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return fb(c.join(""))};function Hd(a){var b,c,d=null==(c=(b=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:c.call(b,"script[nonce]");(b=d?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b)};function Id(a){M.call(this,a)}v(Id,M);n=Id.prototype;n.getEnableSsEngine=function(){return L(this,2)};n.getEnableAwr=function(){return L(this,3)};n.getEnableHelpSuggestions=function(){return L(this,4)};n.getAlohaAutoGaRollout=function(){return L(this,5)};n.getEnableConfigurator=function(){return L(this,6)};n.getEnableMweb=function(){return L(this,7)};n.getEnableCtlConsentCheckbox=function(){return L(this,8)};n.getEnableIframe=function(){return L(this,9)};
n.getEnableScreenshotNudge=function(){return L(this,10)};n.getEnableWebStartupConfigEndpoint=function(){return L(this,11)};n.getEnableJunkNudge=function(){return L(this,12)};n.getEnableConfiguratorLocale=function(){return L(this,13)};n.getEnableTinyNoPointer=function(){return L(this,14)};n.getEnableSupportSessionLogging=function(){return L(this,15)};function Jd(a){M.call(this,a)}v(Jd,M);function Kd(a){return Ld.some(function(b){return b.test(a)})}var Ld=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var Md="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");
function Nd(a){var b;return null==(b=a.formContent)?void 0:b.locale};var Od=ea(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);function Pd(a){var b=Nd(a);b=(b&&Md.includes(b)?Nd(a):"en").replaceAll("-","_").toLowerCase();var c;a=(null==(c=a.initializationData)?0:c.useNightlyRelease)?"nightly":"live";return Gd(Od,a,b)};var Qd;function Rd(a,b,c){if(Qd)return Qd;var d=Pd(a);return Qd=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(e,f){var g=mb(document,"SCRIPT");g.src=cb(d);Hd(g);g.onload=function(){b.feedbackV2GlobalObject?e(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+d.toString())};c.body.appendChild(g)})}
function Sd(a,b,c,d,e){e=void 0===e?!0:e;var f,g,h,k,l;return wa(function(m){switch(m.i){case 1:f=Date.now();var r=Rd(a,c,d);m.i=2;return{value:r};case 2:g=m.m;if(!(e||(null==(k=a.initializationData)?0:k.useNightlyRelease)||(null==(l=a.initializationData)?0:l.isLocalServer))){h=g.initializeFeedbackClient(a,f,b);m.i=3;break}r=g.initializeFeedbackClientAsync(a,f,b);m.i=4;return{value:r};case 4:h=m.m;case 3:return h.initiateAloha(),m.return(h)}})}
function Td(a,b,c){var d=!0;d=void 0===d?!0:d;var e,f,g,h;wa(function(k){f=e=c||x;if(f.isFormOpened)throw g=Error("Form is either loading or already opened"),g.name="DuplicateFormError",g;f.isFormOpened=!0;a.callbacks=a.callbacks||{};h=a.callbacks.onClose||function(){};a.callbacks.onClose=function(l){f.isFormOpened=!1;h(l)};try{return k.return(Sd(a,b,f,e.document,d))}catch(l){throw f.isFormOpened=!1,l;}})};function Ud(a,b){return wa(function(c){return c.return(new Promise(function(d){var e=Vd(null!=b?b:"")+"/aloha_form_properties?productId="+a;xd(e,function(f){var g=f.target;f=null;try{var h=JSON,k=h.stringify;if(g.h){var l=g.h.responseText;0==l.indexOf(")]}'\n")&&(l=l.substring(5));b:{if(x.JSON)try{var m=x.JSON.parse(l);break b}catch(z){}m=Mc(l)}}else m=void 0;var r=k.call(h,m);if(null==r||""==r)f=new Jd;else{var y=JSON.parse(r);if(!Array.isArray(y))throw Error(void 0);f=Nb(Jd,zb(y))}}catch(z){k=new Jd,
m=new Id,m=K(m,5),m=K(m,2),m=K(m,4),m=K(m,8),m=K(m,9),m=K(m,7),m=K(m,10),m=K(m,12),m=K(m,13),m=K(m,14),m=K(m,15),Gb(k),null!=m?Jb(m,Id):m=void 0,f=J(k,1,m)}d(f)},"GET","",{},2E3,!0)}))})}function Vd(a){return Kd(a)?a:"https://www.google.com/tools/feedback"};function Wd(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||x,e=d.document,f=a.nonce||hb(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ba("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,
b);else{d=c+"/load.js?";for(var k in a)b=a[k],null==b||Da(b)||(d+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=mb((e?new ob(9==e.nodeType?e:e.ownerDocument||e.document):Ka||(Ka=new ob)).h,"SCRIPT");f&&a.setAttribute("nonce",f);f=fb(d);a.src=cb(f);Hd(a);e.body.appendChild(a)}}
Aa("userfeedback.api.startFeedback",function(a,b,c){try{"submit"===a.flow||"help"===a.flow?Wd(a,b,c):Ud(a.productId,a.feedbackServerUri).then(function(d){var e=void 0===e?!1:e;var f=Lb(d,1,e);var g=!1;var h=null==f||"object"!==typeof f||(g=Array.isArray(f))||f.aa!==Cb?g?new Id(f):void 0:f;h!==f&&null!=h&&(J(d,1,h,e),yb(h.u,H(d.u)&18));f=h;null==f||H(d.u)&2||(h=f,H(h.u)&2&&(g=Wb(h,!1),g.j=h,h=g),h!==f&&(f=h,J(d,1,f,e)));d=f;e=!Va||(null==d?void 0:d.getEnableMweb());f=!a.tinyNoPointer||(null==d?void 0:
d.getEnableTinyNoPointer());null!=d&&d.getAlohaAutoGaRollout()&&e&&f?(e=c||x,f="DEV"===a.serverEnvironment,h=c||x,h=a.nonce||hb(h),f={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,Ga:void 0,defaultFormInputValues:void 0,
defaultFormInputValuesString:void 0,abuseLink:a.abuseLink},initializationData:{isLocalServer:f,nonce:h,useNightlyRelease:f,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,triggerId:a.triggerId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,
enableAnonymousFeedback:a.enableAnonymousFeedback}},b&&(h=new Map(Object.entries(b)),f.extraData.productSpecificData=h),Td(f,d,e)):Wd(a,b,c)},function(d){d&&"DuplicateFormError"!==d.name&&Wd(a,b,c)})}catch(d){Wd(a,b,c)}});function Xd(a){a=void 0===a?{}:a;this.useNotifications=a.useNotifications||!1;this.operatorDeferredUrl=a.operatorDeferredUrl;this.alphaTestMode=a.alphaTestMode||!1;this.stagingMode=a.stagingMode||!1;this.rosterId=a.rosterId||"talk_roster";this.feedbackId=a.feedbackId||74772;this.moleVersion=a.moleVersion||void 0;this.gstaticBaseUrl=a.gstaticBaseUrl||void 0;this.operatorDeferredBaseUrl=a.operatorDeferredBaseUrl||void 0;this.forceLeftMoles=a.forceLeftMoles||void 0;this.helpCenterName=a.helpCenterName||
null;this.localeName=a.localeName||null;this.document=a.document||document;this.source=a.source||void 0;this.entityId=a.entityId||void 0;this.authUser=a.authUser||void 0;this.appDomain=a.appDomain||void 0;this.apiKey=a.apiKey||void 0;this.hideQueueWidget=a.hideQueueWidget||!1;this.hideMoles=a.hideMoles||!1;this.enableMinimizeRestoreKeyboardShortcut=a.enableMinimizeRestoreKeyboardShortcut||!1;this.showSecondsInChatTranscript=a.showSecondsInChatTranscript||!1;this.settings=a.settings||void 0;this.jsHint=
a.jsHint||void 0;this.xhrTimeoutMs=a.xhrTimeoutMs||1E4;this.enableChatSmartReply=a.enableChatSmartReply||!1;this.isCasesHostPage=a.isCasesHostPage||!1};function Yd(){};/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function V(a,b){this.m=[];this.G=a;this.D=b||null;this.l=this.j=!1;this.i=void 0;this.A=this.J=this.s=!1;this.o=0;this.h=null;this.v=0}C(V,Yd);V.prototype.cancel=function(a){if(this.j)this.i instanceof V&&this.i.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.v--,0>=b.v&&b.cancel())}this.G?this.G.call(this.D,this):this.A=!0;this.j||(a=new Zd(this),$d(this),ae(this,!1,a))}};V.prototype.C=function(a,b){this.s=!1;ae(this,a,b)};function ae(a,b,c){a.j=!0;a.i=c;a.l=!b;be(a)}
function $d(a){if(a.j){if(!a.A)throw new ce(a);a.A=!1}}V.prototype.callback=function(a){$d(this);ae(this,!0,a)};function de(a,b,c,d){a.m.push([b,c,d]);a.j&&be(a)}V.prototype.then=function(a,b,c){var d,e,f=new S(function(g,h){e=g;d=h});de(this,e,function(g){g instanceof Zd?f.cancel():d(g);return ee},this);return f.then(a,b,c)};V.prototype.$goog_Thenable=!0;function fe(a){return Oa(a.m,function(b){return"function"===typeof b[1]})}var ee={};
function be(a){if(a.o&&a.j&&fe(a)){var b=a.o,c=ge[b];c&&(x.clearTimeout(c.h),delete ge[b]);a.o=0}a.h&&(a.h.v--,delete a.h);b=a.i;for(var d=c=!1;a.m.length&&!a.s;){var e=a.m.shift(),f=e[0],g=e[1];e=e[2];if(f=a.l?g:f)try{var h=f.call(e||a.D,b);h===ee&&(h=void 0);void 0!==h&&(a.l=a.l&&(h==b||h instanceof Error),a.i=b=h);if(Tc(b)||"function"===typeof x.Promise&&b instanceof x.Promise)d=!0,a.s=!0}catch(k){b=k,a.l=!0,fe(a)||(c=!0)}}a.i=b;d&&(h=A(a.C,a,!0),d=A(a.C,a,!1),b instanceof V?(de(b,h,d),b.J=!0):
b.then(h,d));c&&(b=new he(b),ge[b.h]=b,a.o=b.h)}function ce(){D.call(this)}C(ce,D);ce.prototype.message="Deferred has already fired";ce.prototype.name="AlreadyCalledError";function Zd(){D.call(this)}C(Zd,D);Zd.prototype.message="Deferred was canceled";Zd.prototype.name="CanceledError";function he(a){this.h=x.setTimeout(A(this.j,this),0);this.i=a}he.prototype.j=function(){delete ge[this.h];throw this.i;};var ge={};function ie(a,b){var c=b||{};b=c.document||document;var d=cb(a).toString(),e=mb((new ob(b)).h,"SCRIPT"),f={ia:e,S:void 0},g=new V(je,f),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){ke(e,!0);var l=new le(1,"Timeout reached for loading script "+d);$d(g);ae(g,!1,l)},k),f.S=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(ke(e,c.Fa||!1,h),g.callback(null))};e.onerror=function(){ke(e,!0,h);var l=new le(0,"Error while loading script "+
d);$d(g);ae(g,!1,l)};f=c.attributes||{};$a(f,{type:"text/javascript",charset:"UTF-8"});jb(e,f);gb(e,a);me(b).appendChild(e);return g}function me(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!==b.length?b[0]:a.documentElement}function je(){if(this&&this.ia){var a=this.ia;a&&"SCRIPT"==a.tagName&&ke(a,!0,this.S)}}
function ke(a,b,c){null!=c&&x.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function le(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);D.call(this,c);this.code=a}C(le,D);function ne(a,b){return oe(a,b).then(function(c){var d=c.responseText;b&&b.Da&&(c=b.Da,0==d.lastIndexOf(c,0)&&(d=d.substring(c.length)));return JSON.parse(d)})}
function oe(a,b){var c=b||{},d=c.na?c.na.h():Qc.h();return ad(new S(function(e,f){var g;try{d.open("GET",a,!0)}catch(l){f(new W("Error opening XHR: "+l.message,a,d))}d.onreadystatechange=function(){if(4==d.readyState){x.clearTimeout(g);var l;!(l=Nc(d.status))&&(l=0===d.status)&&(l=nd(a),l=!("http"==l||"https"==l||""==l));l?e(d):f(new pe(d.status,a,d))}};d.onerror=function(){f(new W("Network error",a,d))};if(c.headers)for(var h in c.headers){var k=c.headers[h];null!=k&&d.setRequestHeader(h,k)}c.withCredentials&&
(d.withCredentials=c.withCredentials);c.responseType&&(d.responseType=c.responseType);c.mimeType&&d.overrideMimeType(c.mimeType);0<c.la&&(g=x.setTimeout(function(){d.onreadystatechange=function(){};d.abort();f(new qe(a,d))},c.la));try{d.send(null)}catch(l){d.onreadystatechange=function(){},x.clearTimeout(g),f(new W("Error sending XHR: "+l.message,a,d))}}),function(e){e instanceof bd&&d.abort();throw e;})}function W(a,b){D.call(this,a+", url="+b);this.url=b}C(W,D);W.prototype.name="XhrError";
function pe(a,b,c){W.call(this,"Request Failed, status="+a,b,c);this.status=a}C(pe,W);pe.prototype.name="XhrHttpError";function qe(a,b){W.call(this,"Request timed out",a,b)}C(qe,W);qe.prototype.name="XhrTimeoutError";function re(){}C(re,Oc);re.prototype.h=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if("undefined"!=typeof XDomainRequest)return new se;throw Error("Unsupported browser");};re.prototype.l=function(){return{}};
function se(){this.h=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText="";this.status=-1;this.statusText="";this.h.onload=A(this.va,this);this.h.onerror=A(this.da,this);this.h.onprogress=A(this.wa,this);this.h.ontimeout=A(this.xa,this)}n=se.prototype;n.open=function(a,b,c){if(null!=c&&!c)throw Error("Only async requests are supported.");this.h.open(a,b)};
n.send=function(a){if(a)if("string"==typeof a)this.h.send(a);else throw Error("Only string data is supported");else this.h.send()};n.abort=function(){this.h.abort()};n.setRequestHeader=function(){};n.getResponseHeader=function(a){return"content-type"==a.toLowerCase()?this.h.contentType:""};n.va=function(){this.status=200;this.responseText=this.h.responseText;te(this,4)};n.da=function(){this.status=500;this.responseText="";te(this,4)};n.xa=function(){this.da()};
n.wa=function(){this.status=200;te(this,1)};function te(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}n.getAllResponseHeaders=function(){return"content-type: "+this.h.contentType};function ue(a){this.config=a instanceof Xd?a:new Xd(a);this.config=ve(this.config);this.h=we(this);this.j=this.config.moleVersion?U():this.h.then(function(b){this.config.moleVersion=b.cbfVersion},function(){},this);this.l=this.h.then(function(b){this.config.settings=this.config.settings?Object.assign({},b.settings,this.config.settings):b.settings},function(){},this);this.h.then(this.i,function(){},this)}
function we(a){return ne(a.config.alphaTestMode?"//ssl.gstatic.com/support/realtime/operatorParamsDev":a.config.stagingMode?"//ssl.gstatic.com/support/realtime/operatorParamsStaging":"//ssl.gstatic.com/support/realtime/operatorParams",{la:a.config.xhrTimeoutMs,na:new re}).then(function(b){if(!b)throw Error("operatorParams is null");return b},function(b){throw b;})}
function xe(a){var b=ye();if(b)return b;if(b=ze())return b=U(b),Ae(b),b;b=Zc([a.j,a.l]).then(function(){return Be(a).then(function(c){var d={document:this.config.document,timeout:this.config.xhrTimeoutMs};this.config.operatorDeferredUrl=c;try{return ie(fb(c),d).then(function(){return x.cs.OperatorDeferred.getInstance(this.config)},function(e){throw e;},this)}catch(e){throw e;}},null,a)},function(){},a);Ae(b);return b}
ue.prototype.i=function(a){(new RegExp(a.eagerLoadHostnamePattern,a.eagerLoadHostnameFlags)).test(this.config.document.location.href)&&ad(xe(this),B(Ce,"Error retrieving OperatorDeferred"))};
function Be(a){return a.config.operatorDeferredUrl?U(a.config.operatorDeferredUrl):a.config.operatorDeferredBaseUrl?(a=a.config.operatorDeferredBaseUrl+"/"+a.config.moleVersion+"/operatordeferred_bin_base__"+a.config.localeName.replace(/-/g,"_").toLowerCase()+".js",U(a)):a.h.then(A(function(b){return"https://ssl.gstatic.com/support/realtime/operator/"+b.cbfVersion+"/operatordeferred_bin_base__"+this.config.localeName.replace(/-/g,"_").toLowerCase()+".js"},a),function(b){throw b;})}
function De(a,b){return xe(a).then(B(function(c,d){d.registerAvailabilityCallbacks(c)},b))}function Ee(a){return xe(a).then(function(b){b.getAvailabilities()})}ue.prototype.V=function(){return xe(this).then(function(a){a.ensureSubscribed()})};function Fe(a,b,c){b=B(function(d,e,f,g,h,k){return k.requestSupport(d,e,f,g,h)},b,c,void 0,!0,void 0);return(c=ze())?(a=b(c),U(a)):xe(a).then(b)}function ze(){return Ba("cs.operatorDeferredInstance")}
function ye(){var a=Ba("cs.operatorDeferredPromise");return a instanceof S?a:null!=a?U(a):null}function Ae(a){Aa("cs.operatorDeferredPromise",a)}function Ce(){}function ve(a){a=Ya(a);a.document=a.document||document;null!=a.localeName&&(a.localeName=a.localeName.replace(/_/g,"-"));a.localeName=a.localeName&&0<=La(Ge,a.localeName)?a.localeName:"en";a.helpCenterName=a.helpCenterName||"chatsupport";a.apiKey=a.apiKey||"AIzaSyB5V4SIBGmrqREm7kf2fBJgPcBMCdUrLzE";return a}var Ge="af am ar ar-XB bg bn ca cs da de el en en-AU en-GB en-XA en-XC es es-419 et eu fa fi fil fr gl gu hi hr hu id is it iw ja kn ko lt lv ml mr ms nl no pl pt-PT pt-BR ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW zh-HK zu".split(" ");function He(a){ue.call(this,a)}v(He,ue);function Ie(a){N.call(this);this.i=a}C(Ie,N);Ie.prototype.h=function(a){return Je(this,a)};function Ke(a,b){a=Object.prototype.hasOwnProperty.call(a,Ea)&&a[Ea]||(a[Ea]=++Fa);return(b?"__wrapper_":"__protected_")+a+"__"}function Je(a,b){var c=Ke(a,!0);b[c]||((b[c]=Le(a,b))[Ke(a,!1)]=b);return b[c]}
function Le(a,b){function c(){if(a.isDisposed())return b.apply(this,arguments);try{return b.apply(this,arguments)}catch(e){var d=e;if(!(d&&"object"===typeof d&&"string"===typeof d.message&&0==d.message.indexOf("Error in protected function: ")||"string"===typeof d&&0==d.indexOf("Error in protected function: ")))throw a.i(d),new Me(d);}}c[Ke(a,!1)]=b;return c}
function Ne(a,b){var c=x.window||x.globalThis,d=c[b];if(!d)throw Error(b+" not on global?");c[b]=function(e,f){"string"===typeof e&&(e=B(Ia,e));e&&(arguments[0]=e=Je(a,e));if(d.apply)return d.apply(this,arguments);var g=e;if(2<arguments.length){var h=Array.prototype.slice.call(arguments,2);g=function(){e.apply(this,h)}}return d(g,f)};c[b][Ke(a,!1)]=d}
Ie.prototype.H=function(){var a=x.window||x.globalThis;var b=a.setTimeout;b=b[Ke(this,!1)]||b;a.setTimeout=b;b=a.setInterval;b=b[Ke(this,!1)]||b;a.setInterval=b;Ie.M.H.call(this)};function Me(a){D.call(this,"Error in protected function: "+(a&&a.message?String(a.message):String(a)),a);(a=a&&a.stack)&&"string"===typeof a&&(this.stack=a)}C(Me,D);function Oe(a,b,c){Q.call(this);this.l=b||null;this.i={};this.A=Pe;this.v=a;if(!c){this.h=null;this.h=new Ie(A(this.o,this));Ne(this.h,"setTimeout");Ne(this.h,"setInterval");a=this.h;b=x.window||x.globalThis;c=["requestAnimationFrame","mozRequestAnimationFrame","webkitAnimationFrame","msRequestAnimationFrame"];for(var d=0;d<c.length;d++){var e=c[d];c[d]in b&&Ne(a,e)}a=this.h;bc=!0;b=A(a.h,a);for(c=0;c<$b.length;c++)$b[c](b);ac.push(a)}}C(Oe,Q);function Qe(a){O.call(this,"a");this.error=a}C(Qe,O);
function Pe(a,b,c,d){if(d instanceof Map){var e={};d=t(d);for(var f=d.next();!f.done;f=d.next()){var g=t(f.value);f=g.next().value;g=g.next().value;e[f]=g}}else e=d;xd(a,null,b,c,e)}
Oe.prototype.o=function(a,b){a=a.error||a;b=b?Ya(b):{};a instanceof Error&&$a(b,a.__closure__error__context__984382||{});var c=qc(a);if(this.l)try{this.l(c,b)}catch(m){}var d=c.message.substring(0,1900);if(!(a instanceof D)||a.h){a=c.stack;try{var e=sd(this.v,"script",c.fileName,"error",d,"line",c.lineNumber);a:{for(var f in this.i){var g=!1;break a}g=!0}if(!g){g=e;var h=rd(this.i);e=od(g,h)}h={};h.trace=a;if(b)for(var k in b)h["context."+k]=b[k];var l=rd(h);this.A(e,"POST",l,this.C)}catch(m){}}try{R(this,
new Qe(c,b))}catch(m){}};Oe.prototype.H=function(){var a=this.h;a&&"function"==typeof a.Z&&a.Z();Oe.M.H.call(this)};function X(a,b,c,d,e,f){var g=new Oe("//www.google.com/tools/feedback/jserror",void 0,!0);this.l=A(g.o,g);this.A=a;this.D=c||"en";this.C=b||!1;this.G=!!d;this.v=e;this.i=this.h=null;this.s=f}
function Re(a,b,c,d,e,f){if(Se())return null;window.top.GOOGLE_HELP_CHAT_OPERATOR_V2=He;if(window.top.GOOGLE_HELP_CHAT_SUPPORT)return null;a=new X(a,b,c,d,e,f);window.top.GOOGLE_HELP_CHAT_SUPPORT=a;Te(a);window.addEventListener("message",function(g){"helpPanelEnsureSubscribed"===g.data&&Ue.test(g.origin)&&(window.top.GOOGLE_HELP_CHAT_SUPPORT.V(),console.log("Chat ensureSubscribed called by HP event listener."))});return a}
function Se(){var a=window;try{return null==a||null==a.top||null==a.top.document}catch(b){return!0}}function Te(a){var b={helpCenterName:a.A,localeName:a.D,source:1,rosterId:"roster-for-Google-Help",isRtl:a.C,alphaTestMode:!1,stagingMode:a.G,timeoutMs:2E4,authUser:a.v,apiKey:a.s},c=lb("DIV",{id:"roster-for-Google-Help",style:"display: none"});window.top.document.body.appendChild(c);try{a.j=new He(b)}catch(d){a.l(d)}}function Ve(a,b,c){if(null!=b&&null!=c){var d={};d[b]=c;ad(De(a.j,d),a.l)}}n=X.prototype;
n.ja=function(a){this.h=a;Ve(this,this.h,this.m)};n.ka=function(a){this.i=a;Ve(this,this.i,this.o)};n.Ba=function(a){this.m=a;Ve(this,this.h,this.m)};n.Ca=function(a){this.o=a;Ve(this,this.i,this.o)};n.oa=function(a){null!=this.h&&ad(Fe(this.j,this.h,a),this.l)};n.Aa=function(a){null!=this.i&&ad(Fe(this.j,this.i,a),this.l)};n.ea=function(){null==this.h&&null==this.i||ad(Ee(this.j),this.l)};n.V=function(){this.j.V()};var Ue=new RegExp(/^https:\/\/(pay.*|billing-ads-qa-devel|daily-1|dasher-workspace-*|meet-dev|gpay-landing.*|spot.*|tokenized.*)?\.?(bpui0|developers|corp|meet|payments|pay|play|sandbox|workspace)\.(google|youtube|admob)\.\w+\.?\w*/);
X.prototype.setChatPool=X.prototype.ja;X.prototype.setHangoutPool=X.prototype.ka;X.prototype.setChatCallback=X.prototype.Ba;X.prototype.setHangoutCallback=X.prototype.Ca;X.prototype.requestChatSupport=X.prototype.oa;X.prototype.requestHangoutSupport=X.prototype.Aa;X.prototype.getAvailabilities=X.prototype.ea;X.prototype.ensureSubscribed=X.prototype.V;function We(){}We.prototype.next=function(){return Xe};var Xe={done:!0,value:void 0};We.prototype.P=function(){return this};function Ye(a){if(a instanceof Y||a instanceof Ze||a instanceof Z)return a;if("function"==typeof a.next)return new Y(function(){return a});if("function"==typeof a[Symbol.iterator])return new Y(function(){return a[Symbol.iterator]()});if("function"==typeof a.P)return new Y(function(){return a.P()});throw Error("Not an iterator or iterable.");}function Y(a){this.h=a}Y.prototype.P=function(){return new Ze(this.h())};Y.prototype[Symbol.iterator]=function(){return new Z(this.h())};Y.prototype.i=function(){return new Z(this.h())};
function Ze(a){this.h=a}v(Ze,We);Ze.prototype.next=function(){return this.h.next()};Ze.prototype[Symbol.iterator]=function(){return new Z(this.h)};Ze.prototype.i=function(){return new Z(this.h)};function Z(a){Y.call(this,function(){return a});this.j=a}v(Z,Y);Z.prototype.next=function(){return this.j.next()};function $e(){};function af(){}C(af,$e);af.prototype[Symbol.iterator]=function(){return Ye(this.P(!0)).i()};function bf(a){this.h=a}C(bf,af);bf.prototype.set=function(a,b){try{this.h.setItem(a,b)}catch(c){if(0==this.h.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};bf.prototype.get=function(a){a=this.h.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};function cf(a){a.h.removeItem("GOOGLE_HELP_SESSION_STATE")}
bf.prototype.P=function(a){var b=0,c=this.h,d=new We;d.next=function(){if(b>=c.length)return Xe;var e=c.key(b++);if(a)return{value:e,done:!1};e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return{value:e,done:!1}};return d};bf.prototype.key=function(a){return this.h.key(a)};function df(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.h=a}C(df,bf);function ef(){N.call(this);this.h=new df}v(ef,N);(function(a){var b=a.helpCenterPath,c=a.locale,d=a.authuser,e=a.escalationJSONString,f=!!a.useStagingServer;a=a.apiKey;var g=document.body;a:{var h=9==g.nodeType?g:g.ownerDocument||g.document;if(h.defaultView&&h.defaultView.getComputedStyle&&(h=h.defaultView.getComputedStyle(g,null))){h=h.direction||h.getPropertyValue("direction")||"";break a}h=""}b=Re(b,"rtl"==(h||(g.currentStyle?g.currentStyle.direction:null)||g.style&&g.style.direction),c,f,d,a);c=new ef;e&&(cf(c.h),e={ra:JSON.parse(e).ra},e.sessionTimestamp=
(new Date).getTime(),c.h.set("GOOGLE_HELP_SESSION_STATE",JSON.stringify(e)));if(e=c.h.get("GOOGLE_HELP_SESSION_STATE")){if(e=JSON.parse(e),d=(new Date).getTime(),f=e.sessionTimestamp,!f||"number"!==typeof f||d>f+6E4)cf(c.h),e=null}else e=null;c=(e||{}).escalationOptions;b&&c&&(e=c.hangout||{},(c=(c.chat||{}).chat_pool_id)&&b.ja(c),(e=e.hangout_pool_id)&&b.ka(e),b.ea())}).apply(x,x.GOOGLE_HELP_CHAT_ARGUMENTS);}).call(this);
